
import '../models/career_models.dart' show CareerBank, EducationPath;

final List<CareerBank> sampleCareers = [
  // 1. Technology – Engineering
  CareerBank(
    careerId: "1",
    title: "Software Engineer",
    industry: "Technology – Engineering",
    description: "Design, develop, and maintain software applications.",
    skills: ["Programming", "Problem-solving", "Teamwork"],
    salaryRange: "1000 – 2000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Computer Science",
      courses: ["Data Structures", "Algorithms", "Databases"],
      certificates: ["AWS", "Google Cloud"],
      duration: "4 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "15,000 USD",
    ),
  ),
  CareerBank(
    careerId: "2",
    title: "Civil Engineer",
    industry: "Technology – Engineering",
    description: "Plan, design, and oversee construction projects.",
    skills: ["AutoCAD", "Project Management", "Structural Analysis"],
    salaryRange: "900 – 1800 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Civil Engineering",
      courses: ["Structural Engineering", "Construction Materials"],
      certificates: ["PMP"],
      duration: "4 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "14,000 USD",
    ),
  ),

  // 2. Economics – Management
  CareerBank(
    careerId: "3",
    title: "Marketing Specialist",
    industry: "Economics – Management",
    description: "Execute marketing campaigns and analyze trends.",
    skills: ["Market Analysis", "Communication", "Content Creation"],
    salaryRange: "800 – 1500 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Marketing",
      courses: ["Digital Marketing", "Consumer Behavior"],
      certificates: ["Google Ads", "Facebook Blueprint"],
      duration: "4 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "12,000 USD",
    ),
  ),
  CareerBank(
    careerId: "4",
    title: "Financial Analyst",
    industry: "Economics – Management",
    description: "Evaluate financial data to support decision-making.",
    skills: ["Excel", "Financial Modeling", "Critical Thinking"],
    salaryRange: "1000 – 2000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Finance",
      courses: ["Corporate Finance", "Accounting"],
      certificates: ["CFA"],
      duration: "4 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "13,000 USD",
    ),
  ),

  // 3. Healthcare
  CareerBank(
    careerId: "5",
    title: "Nurse",
    industry: "Healthcare",
    description: "Provide patient care and assist doctors.",
    skills: ["Patient Care", "Empathy", "Medical Knowledge"],
    salaryRange: "700 – 1200 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Nursing",
      courses: ["Anatomy", "Clinical Practice"],
      certificates: ["CPR", "BLS"],
      duration: "4 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "10,000 USD",
    ),
  ),
  CareerBank(
    careerId: "6",
    title: "Pharmacist",
    industry: "Healthcare",
    description: "Prepare and dispense medications, advise patients.",
    skills: ["Pharmacology", "Communication", "Detail-oriented"],
    salaryRange: "900 – 1600 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Pharmacy",
      courses: ["Pharmacology", "Chemistry"],
      certificates: ["Drug Safety"],
      duration: "5 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "15,000 USD",
    ),
  ),

  // 4. Education – Teaching
  CareerBank(
    careerId: "7",
    title: "High School Teacher",
    industry: "Education – Teaching",
    description: "Teach academic subjects to secondary students.",
    skills: ["Communication", "Pedagogy", "Classroom Management"],
    salaryRange: "600 – 1200 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Education",
      courses: ["Pedagogy", "Subject Methods"],
      certificates: ["TESOL"],
      duration: "4 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "8,000 USD",
    ),
  ),
  CareerBank(
    careerId: "8",
    title: "University Lecturer",
    industry: "Education – Teaching",
    description: "Teach and research at higher education level.",
    skills: ["Research", "Teaching", "Critical Thinking"],
    salaryRange: "900 – 2000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Master or PhD",
      courses: ["Specialized Courses", "Research Methods"],
      certificates: ["Academic Writing"],
      duration: "6+ years",
      careerLevel: "Mid – Senior",
      estimatedCost: "20,000 USD",
    ),
  ),

  // 5. Agriculture – Forestry – Fishery
  CareerBank(
    careerId: "9",
    title: "Agronomist",
    industry: "Agriculture – Forestry – Fishery",
    description: "Develop and improve agricultural practices.",
    skills: ["Soil Science", "Crop Management"],
    salaryRange: "700 – 1300 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Agriculture",
      courses: ["Plant Science", "Irrigation"],
      certificates: ["Sustainable Farming"],
      duration: "4 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "9,000 USD",
    ),
  ),
  CareerBank(
    careerId: "10",
    title: "Fisheries Manager",
    industry: "Agriculture – Forestry – Fishery",
    description: "Oversee fish farming and aquaculture production.",
    skills: ["Aquaculture", "Resource Management"],
    salaryRange: "700 – 1200 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Fisheries",
      courses: ["Marine Biology", "Aquaculture Systems"],
      certificates: ["Sustainable Fisheries"],
      duration: "4 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "9,500 USD",
    ),
  ),

  // 6. Culture – Arts – Tourism
  CareerBank(
    careerId: "11",
    title: "Tour Guide",
    industry: "Culture – Arts – Tourism",
    description: "Guide tourists and provide cultural insights.",
    skills: ["Communication", "Foreign Languages", "Public Speaking"],
    salaryRange: "500 – 1000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Tourism",
      courses: ["Hospitality", "Tour Management"],
      certificates: ["Tour Guide License"],
      duration: "3 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "7,000 USD",
    ),
  ),
  CareerBank(
    careerId: "12",
    title: "Graphic Designer",
    industry: "Culture – Arts – Tourism",
    description: "Create visuals for brands and media.",
    skills: ["Photoshop", "Illustrator", "Creativity"],
    salaryRange: "600 – 1200 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Design",
      courses: ["Visual Arts", "Digital Design"],
      certificates: ["Adobe Certified"],
      duration: "4 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "9,000 USD",
    ),
  ),

  // 7. Law – Security – Defense
  CareerBank(
    careerId: "13",
    title: "Lawyer",
    industry: "Law – Security – Defense",
    description: "Provide legal advice and represent clients in court.",
    skills: ["Legal Knowledge", "Negotiation", "Research"],
    salaryRange: "1200 – 3000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Bachelor in Law",
      courses: ["Civil Law", "Criminal Law"],
      certificates: ["Bar License"],
      duration: "5 years",
      careerLevel: "Mid – Senior",
      estimatedCost: "18,000 USD",
    ),
  ),
  CareerBank(
    careerId: "14",
    title: "Police Officer",
    industry: "Law – Security – Defense",
    description: "Maintain public safety and enforce laws.",
    skills: ["Physical Fitness", "Law Knowledge", "Discipline"],
    salaryRange: "800 – 1500 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Police Academy Training",
      courses: ["Criminal Justice", "Investigation"],
      certificates: ["Law Enforcement"],
      duration: "3 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "6,000 USD",
    ),
  ),

  // 8. General Labor – Services
  CareerBank(
    careerId: "15",
    title: "Electrician",
    industry: "General Labor – Services",
    description: "Install and repair electrical systems.",
    skills: ["Technical Skills", "Problem-solving"],
    salaryRange: "600 – 1000 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Vocational Training",
      courses: ["Electrical Systems"],
      certificates: ["Electrician License"],
      duration: "2 years",
      careerLevel: "Entry – Mid",
      estimatedCost: "3,000 USD",
    ),
  ),
  CareerBank(
    careerId: "16",
    title: "Chef",
    industry: "General Labor – Services",
    description: "Prepare meals and manage kitchen operations.",
    skills: ["Cooking", "Creativity", "Time Management"],
    salaryRange: "500 – 1200 USD",
    imageUrl: "",
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    educationPath: EducationPath(
      degree: "Culinary School",
      courses: ["Culinary Arts", "Nutrition"],
      certificates: ["Food Safety"],
      duration: "2 – 3 years",
      careerLevel: "Entry – Senior",
      estimatedCost: "4,500 USD",
    ),
  ),
];
